const rankToInt = new Map([
  ['UNRANKED', 0],
  ['IRON IV', 1],
  ['IRON III', 2],
  ['IRON II', 3],
  ['IRON I', 4],
  ['BRONZE IV', 5],
  ['BRONZE III', 6],
  ['BRONZE II', 7],
  ['BRONZE I', 8],
  ['SILVER IV', 9],
  ['SILVER III', 10],
  ['SILVER II', 11],
  ['SILVER I', 12],
  ['GOLD IV', 13],
  ['GOLD III', 14],
  ['GOLD II', 15],
  ['GOLD I', 16],
  ['PLATINUM IV', 17],
  ['PLATINUM III', 18],
  ['PLATINUM II', 19],
  ['PLATINUM I', 20],
  ['DIAMOND IV', 21],
  ['DIAMOND III', 22],
  ['DIAMOND II', 23],
  ['DIAMOND I', 24],
  ['MASTER', 25],
  ['GRANDMASTER', 26],
  ['CHALLENGER', 27],
]);

const intToRank = new Map([
  [0, 'UNRANKED'],
  [1, 'IRON IV'],
  [2, 'IRON III'],
  [3, 'IRON II'],
  [4, 'IRON I'],
  [5, 'BRONZE IV'],
  [6, 'BRONZE III'],
  [7, 'BRONZE II'],
  [8, 'BRONZE I'],
  [9, 'SILVER IV'],
  [10, 'SILVER III'],
  [11, 'SILVER II'],
  [12, 'SILVER I'],
  [13, 'GOLD IV'],
  [14, 'GOLD III'],
  [15, 'GOLD II'],
  [16, 'GOLD I'],
  [17, 'PLATINUM IV'],
  [18, 'PLATINUM III'],
  [19, 'PLATINUM II'],
  [20, 'PLATINUM I'],
  [21, 'DIAMOND IV'],
  [22, 'DIAMOND III'],
  [23, 'DIAMOND II'],
  [24, 'DIAMOND I'],
  [25, 'MASTER'],
  [26, 'GRANDMASTER'],
  [27, 'CHALLENGER'],
]);

module.exports = {
  rankToInt,
  intToRank,
};
